# ==============================================================================
# Rubellite::Docs Documentation System - Master Index & Navigation Hub
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# ==============================================================================

{% unless flag?(:release) %}
module Rubellite
  # The `Rubellite::Docs` module is the authoritative technical reference and documentation guide.
  #
  # ## Learning Tracks & Topic Index
  #
  # The documentation is paced into 3 distinct tracks:
  #
  # ### 1. Getting started (`A_GETTING_STARTED`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>OVERVIEW</code></td>
  #       <td><strong>Getting Started & System Architecture</strong></td>
  #       <td>Introduction to Rubellite, the bidirectional Crystal <-> Ruby interop engine.</td>
  #     </tr>
  #     <tr>
  #       <td><code>QUICKSTART</code></td>
  #       <td><strong>Quickstart Guide & Usage Patterns</strong></td>
  #       <td>Step-by-step tutorial on bootstrapping Rubellite, calling methods, and handling errors.</td>
  #     </tr>
  #     <tr>
  #       <td><code>TYPE_SYSTEM</code></td>
  #       <td><strong>Type Conversions & Value Marshaling</strong></td>
  #       <td>Bidirectional marshaling between Crystal native types and CRuby VALUE handles.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 2. Advanced features (`B_ADVANCED_FEATURES`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>C_API_AND_MEMORY</code></td>
  #       <td><strong>C API, Memory Management & GC Coordination</strong></td>
  #       <td>Deep dive into LibRuby bindings, Win32 symbol collision isolation, and dual-GC lifecycles.</td>
  #     </tr>
  #     <tr>
  #       <td><code>CHANNEL_CONCURRENCY</code></td>
  #       <td><strong>Channel Concurrency & Fiber Interop</strong></td>
  #       <td>Bridging Crystal CSP channels with Ruby scripts and managing the Global VM Lock (GVL).</td>
  #     </tr>
  #     <tr>
  #       <td><code>SPINEL_AOT</code></td>
  #       <td><strong>Spinel AOT Native Compilation Fast-Path</strong></td>
  #       <td>High-performance Ahead-Of-Time and JIT kernel acceleration for compute-heavy algorithms.</td>
  #     </tr>
  #     <tr>
  #       <td><code>R2_FORENSICS</code></td>
  #       <td><strong>Binary Forensics & ABI Auditing via Radare2</strong></td>
  #       <td>Static and dynamic binary analysis of libruby exports, symbols, and ABI compatibility.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  # ### 3. Versioning and releases (`C_VERSIONING_AND_RELEASES`)
  # <table>
  #   <thead>
  #     <tr>
  #       <th>Submodule</th>
  #       <th>Title</th>
  #       <th>Description</th>
  #     </tr>
  #   </thead>
  #   <tbody>
  #     <tr>
  #       <td><code>CARBON_VERSIONING</code></td>
  #       <td><strong>Internal Versioning & Release Engineering with Carbon</strong></td>
  #       <td>Automated commit-based versioning, zero-friction Git hooks, changelogs, and badge management.</td>
  #     </tr>
  #     <tr>
  #       <td><code>RUBY_VERSION_TRACKING</code></td>
  #       <td><strong>Upstream Ruby Compatibility Branches & Dual Versioning</strong></td>
  #       <td>Managing 1-commit branches off main and tags to track specific Ruby releases.</td>
  #     </tr>
  #   </tbody>
  # </table>
  #
  module Docs
    # **Quick-Start Commands**: Essential commands for building, running, and testing.
    #
    # #### Rubellite Commands:
    # ```bash
    # shards install
    # crystal spec
    # bin/jasper build
    # crystal docs
    # ```
    def self.topic_01_quick_start : Nil; end

    # **Learning Tracks & Reading Paths**: Curated reading order from beginner to advanced.
    #
    # #### Structured Learning Tracks
    #
    # ##### 1. Getting started (`A_GETTING_STARTED`)
    # - `A_GETTING_STARTED::OVERVIEW`: **Getting Started & System Architecture** &mdash; Introduction to Rubellite, the bidirectional Crystal &lt;-&gt; Ruby interop engine.
    # - `A_GETTING_STARTED::QUICKSTART`: **Quickstart Guide & Usage Patterns** &mdash; Step-by-step tutorial on bootstrapping Rubellite, calling methods, and handling errors.
    # - `A_GETTING_STARTED::TYPE_SYSTEM`: **Type Conversions & Value Marshaling** &mdash; Bidirectional marshaling between Crystal native types and CRuby VALUE handles.
    #
    # ##### 2. Advanced features (`B_ADVANCED_FEATURES`)
    # - `B_ADVANCED_FEATURES::C_API_AND_MEMORY`: **C API, Memory Management & GC Coordination** &mdash; Deep dive into LibRuby bindings, Win32 symbol collision isolation, and dual-GC lifecycles.
    # - `B_ADVANCED_FEATURES::CHANNEL_CONCURRENCY`: **Channel Concurrency & Fiber Interop** &mdash; Bridging Crystal CSP channels with Ruby scripts and managing the Global VM Lock (GVL).
    # - `B_ADVANCED_FEATURES::SPINEL_AOT`: **Spinel AOT Native Compilation Fast-Path** &mdash; High-performance Ahead-Of-Time and JIT kernel acceleration for compute-heavy algorithms.
    # - `B_ADVANCED_FEATURES::R2_FORENSICS`: **Binary Forensics & ABI Auditing via Radare2** &mdash; Static and dynamic binary analysis of libruby exports, symbols, and ABI compatibility.
    #
    # ##### 3. Versioning and releases (`C_VERSIONING_AND_RELEASES`)
    # - `C_VERSIONING_AND_RELEASES::CARBON_VERSIONING`: **Internal Versioning & Release Engineering with Carbon** &mdash; Automated commit-based versioning, zero-friction Git hooks, changelogs, and badge management.
    # - `C_VERSIONING_AND_RELEASES::RUBY_VERSION_TRACKING`: **Upstream Ruby Compatibility Branches & Dual Versioning** &mdash; Managing 1-commit branches off main and tags to track specific Ruby releases.
    #
    def self.topic_02_reading_paths : Nil; end

    # **Master Table of Contents**: Complete hierarchical topic index.
    #
    # #### Complete Documentation Index
    #
    # ##### `A_GETTING_STARTED`
    # - `A_GETTING_STARTED::OVERVIEW`: **Getting Started & System Architecture** &mdash; Introduction to Rubellite, the bidirectional Crystal &lt;-&gt; Ruby interop engine.
    # - `A_GETTING_STARTED::QUICKSTART`: **Quickstart Guide & Usage Patterns** &mdash; Step-by-step tutorial on bootstrapping Rubellite, calling methods, and handling errors.
    # - `A_GETTING_STARTED::TYPE_SYSTEM`: **Type Conversions & Value Marshaling** &mdash; Bidirectional marshaling between Crystal native types and CRuby VALUE handles.
    #
    # ##### `B_ADVANCED_FEATURES`
    # - `B_ADVANCED_FEATURES::C_API_AND_MEMORY`: **C API, Memory Management & GC Coordination** &mdash; Deep dive into LibRuby bindings, Win32 symbol collision isolation, and dual-GC lifecycles.
    # - `B_ADVANCED_FEATURES::CHANNEL_CONCURRENCY`: **Channel Concurrency & Fiber Interop** &mdash; Bridging Crystal CSP channels with Ruby scripts and managing the Global VM Lock (GVL).
    # - `B_ADVANCED_FEATURES::SPINEL_AOT`: **Spinel AOT Native Compilation Fast-Path** &mdash; High-performance Ahead-Of-Time and JIT kernel acceleration for compute-heavy algorithms.
    # - `B_ADVANCED_FEATURES::R2_FORENSICS`: **Binary Forensics & ABI Auditing via Radare2** &mdash; Static and dynamic binary analysis of libruby exports, symbols, and ABI compatibility.
    #
    # ##### `C_VERSIONING_AND_RELEASES`
    # - `C_VERSIONING_AND_RELEASES::CARBON_VERSIONING`: **Internal Versioning & Release Engineering with Carbon** &mdash; Automated commit-based versioning, zero-friction Git hooks, changelogs, and badge management.
    # - `C_VERSIONING_AND_RELEASES::RUBY_VERSION_TRACKING`: **Upstream Ruby Compatibility Branches & Dual Versioning** &mdash; Managing 1-commit branches off main and tags to track specific Ruby releases.
    #
    def self.topic_03_table_of_contents : Nil; end

    # :nodoc:
    def self.quick_start : Nil; topic_01_quick_start; end
    # :nodoc:
    def self.reading_paths : Nil; topic_02_reading_paths; end
    # :nodoc:
    def self.table_of_contents : Nil; topic_03_table_of_contents; end
  end
end

require "./docs/a_getting_started/overview"
require "./docs/a_getting_started/quickstart"
require "./docs/a_getting_started/type_system"
require "./docs/b_advanced_features/c_api_and_memory"
require "./docs/b_advanced_features/channel_concurrency"
require "./docs/b_advanced_features/spinel_aot"
require "./docs/b_advanced_features/r2_forensics"
require "./docs/c_versioning_and_releases/carbon_versioning"
require "./docs/c_versioning_and_releases/ruby_version_tracking"

alias Docs = ::Rubellite::Docs
alias Rubellite::Documentation = ::Rubellite::Docs
{% end %}
