require "./engine_spec"
require "./value_spec"
require "./conversion_spec"
require "./methods_and_blocks_spec"
require "./exceptions_spec"
require "./channel_concurrency_spec"
require "./macros_spec"
require "./spinel_spec"
require "./r2_diagnostics_spec"
require "./auto_init_and_lifecycle_spec"
require "./value_ergonomics_spec"
require "./bidirectional_export_spec"
require "./proxy_advanced_spec"
require "./stress_and_edge_cases_spec"

