# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Rubellite
  module Docs
    module C_VERSIONING_AND_RELEASES
      # # Internal Versioning & Release Engineering with Carbon
      #
      # Rubellite adopts **Carbon** for automated, monotonic version management following the
      # Lapis versioning standard: `<major>.<minor>.<commit_number>`.
      #
      # Every Git commit automatically bumps the commit number across project manifests,
      # while non-destructive changelog management (`changelog.yml` -> `CHANGELOG.md`) tracks features,
      # fixes, and breaking milestones.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Carbon Version Lifecycle & CLI Commands</strong></td>
      #       <td><code>.topic_01_version_lifecycle</code></td>
      #       <td>Managing version bumps, synchronization, and pre-commit hooks.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - shard.yml
      # - badges.yml
      # - changelog.yml
      # - CHANGELOG.md
      # - src/rubellite/version.cr
      #
      module CARBON_VERSIONING
        # **Carbon Version Lifecycle & CLI Commands**: Managing version bumps, synchronization, and pre-commit hooks.
        #
        # Carbon automates the entire release pipeline:
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Command</th>
        #       <th>Description</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>`carbon check`</td>
        #       <td>Verifies whether `shard.yml` matches Git commit count</td>
        #     </tr>
        #     <tr>
        #       <td>`carbon bump`</td>
        #       <td>Manually or via hook advances the commit index</td>
        #     </tr>
        #     <tr>
        #       <td>`carbon bump --minor`</td>
        #       <td>Increments minor version for new feature milestones</td>
        #     </tr>
        #     <tr>
        #       <td>`carbon changelog`</td>
        #       <td>Syncs new Git commits into `changelog.yml` and compiles `CHANGELOG.md`</td>
        #     </tr>
        #     <tr>
        #       <td>`carbon badges`</td>
        #       <td>Renders dynamic badges into `README.md`</td>
        #     </tr>
        #     <tr>
        #       <td>`carbon doctor`</td>
        #       <td>Audits repository health, hooks, and changelogs</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # #### Working Examples
        #
        # ```bash
        # # Audit repository health and version alignment
        # bin/carbon check
        # bin/carbon doctor
        #
        # # Update changelog and badges
        # bin/carbon changelog
        # bin/carbon badges --render
        # ```
        #
        # #### Common Pitfalls & Safety Caveats
        #
        # - **Warning**: Never manually edit the commit counter in shard.yml; let Carbon hooks maintain it.
        #
        # #### Frequently Asked Questions (FAQ)
        #
        # - **Q: How do Git pre-commit hooks work?**
        #   A: The hook executes `carbon bump --hook`, which idempotently updates and stages shard.yml and version.cr.
        #
        def self.topic_01_version_lifecycle : Nil; end
      end
    end
  end
end
{% end %}
