# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Rubellite
  module Docs
    module C_VERSIONING_AND_RELEASES
      # # Upstream Ruby Compatibility Branches & Dual Versioning
      #
      # Following the architectural convention established by the **Lapis** project, Rubellite
      # employs a **dual versioning system**:
      #
      # 1. **Primary Branch Releases (`rubellite-X.Y.Z`)**: Major, minor, and patch releases
      #    of the Rubellite shard cut on the primary development branch (`main`).
      # 2. **Ruby Tracking Branches (`X.Y.Z`) & Tags (`ruby-X.Y.Z`)**: Dedicated single-commit branches
      #    forked directly from `main` that configure Rubellite for a specific upstream Ruby version
      #    (e.g. `4.0.5`, `3.4.0`) via `ruby-version.yml`.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Branch & Tag Structure</strong></td>
      #       <td><code>.topic_01_dual_versioning_workflow</code></td>
      #       <td>How upstream Ruby releases are tracked without cluttering primary branch history.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - ruby-version.yml
      # - scripts/ruby_version_branch.cr
      # - shard.yml
      #
      module RUBY_VERSION_TRACKING
        # **Branch & Tag Structure**: How upstream Ruby releases are tracked without cluttering primary branch history.
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Concept</th>
        #       <th>Identifier</th>
        #       <th>Description</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>**Primary Branch**</td>
        #       <td>`main`</td>
        #       <td>Ongoing feature and shard development</td>
        #     </tr>
        #     <tr>
        #       <td>**Shard Release Tag**</td>
        #       <td>`rubellite-0.1.6`</td>
        #       <td>Tagged on `main` for shard milestone releases</td>
        #     </tr>
        #     <tr>
        #       <td>**Ruby Branch**</td>
        #       <td>`4.0.5`</td>
        #       <td>1-commit branch off `main` for Ruby 4.0.5</td>
        #     </tr>
        #     <tr>
        #       <td>**Ruby Release Tag**</td>
        #       <td>`ruby-4.0.5`</td>
        #       <td>Annotated tag on the Ruby compatibility branch</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # Each Ruby tracking branch contains a single commit incorporating:
        # - `ruby-version.yml`: Declares target Ruby version, ABI version, and flags.
        # - Any version-specific C API workarounds or compiler configurations.
        #
        # #### Working Examples
        #
        # ```bash
        # # Create a Ruby 4.0.5 tracking branch and tag using the automated helper
        # crystal run scripts/ruby_version_branch.cr -- 4.0.5
        #
        # # Check git branch and tag graph
        # git log --graph --oneline --all
        # ```
        #
        # #### Common Pitfalls & Safety Caveats
        #
        # - **Warning**: Never merge a Ruby version branch back into main. Ruby version branches are terminal single-commit branches off main.
        #
        # #### Frequently Asked Questions (FAQ)
        #
        # - **Q: Why use separate 1-commit branches instead of tags alone?**
        #   A: Branches allow users and CI matrices to target a specific Ruby version (`branch: 4.0.5`) in their shard.yml manifests.
        #
        def self.topic_01_dual_versioning_workflow : Nil; end
      end
    end
  end
end
{% end %}
