# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Rubellite
  module Docs
    module A_GETTING_STARTED
      # # Getting Started & System Architecture
      #
      # Rubellite is a high-performance interop framework designed to connect the Crystal
      # and Ruby programming environments with zero overhead.
      #
      # By pairing Crystal's LLVM-compiled speed with CRuby's expansive dynamic ecosystem,
      # Rubellite enables developers to execute Ruby code directly within Crystal fibers,
      # share native types, invoke methods with Crystal blocks, and bridge Crystal Channels
      # with Ruby concurrency primitives.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Architectural Principles & Layering</strong></td>
      #       <td><code>.topic_01_architecture</code></td>
      #       <td>Breakdown of Rubellite's three core runtime layers.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - shard.yml
      # - src/rubellite.cr
      # - src/rubellite/engine.cr
      #
      module OVERVIEW
        # **Architectural Principles & Layering**: Breakdown of Rubellite's three core runtime layers.
        #
        # Rubellite is structured into three distinct layers:
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Layer</th>
        #       <th>Primary Role</th>
        #       <th>Location</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>**Crystal Host**</td>
        #       <td>Native execution, fiber scheduling, memory bounds</td>
        #       <td>`src/rubellite/`</td>
        #     </tr>
        #     <tr>
        #       <td>**C API Bridge**</td>
        #       <td>Direct bindings to MRI `libruby`, symbol hygiene</td>
        #       <td>`src/rubellite/c_api.cr`</td>
        #     </tr>
        #     <tr>
        #       <td>**Diagnostics**</td>
        #       <td>Radare2 symbol auditing, import library generation</td>
        #       <td>`src/rubellite/diagnostics/`</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # Rubellite manages GC safety across both engines: Crystal's Boehm GC and Ruby's
        # compacting garbage collector coordinate to ensure unboxed primitives and
        # heap-allocated Ruby objects remain valid across calls.
        #
        # #### Working Examples
        #
        # ```crystal
        # require "rubellite"
        #
        # # Initialize the embedded Ruby VM
        # Rubellite.init
        #
        # # Evaluate a Ruby expression and unbox the result
        # result = Rubellite.eval("2 + 2")
        # puts "Result: #{result.to_i64}" # => 4
        #
        # # Clean up VM state on shutdown
        # Rubellite.cleanup
        # ```
        #
        # #### Common Pitfalls & Safety Caveats
        #
        # - **Warning**: Always call Rubellite.init before evaluating code or allocating Ruby values.
        # - **Warning**: Ensure Rubellite.cleanup is invoked during shutdown to run Ruby at_exit handlers.
        #
        # #### Frequently Asked Questions (FAQ)
        #
        # - **Q: Does Rubellite require a standalone Ruby installation?**
        #   A: Yes, Rubellite links dynamically against the system's CRuby shared library (libruby).
        #
        # - **Q: What versions of Ruby are supported?**
        #   A: CRuby 3.2 through 4.x are supported, with dedicated version branches tracking upstream releases.
        #
        def self.topic_01_architecture : Nil; end
      end
    end
  end
end
{% end %}
