# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Rubellite
  module Docs
    module A_GETTING_STARTED
      # # Quickstart Guide & Usage Patterns
      #
      # This guide provides hands-on code examples for embedding Rubellite into your Crystal project,
      # evaluating Ruby scripts, calling Ruby methods with arguments, and executing blocks.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Evaluating Scripts & Invoking Methods</strong></td>
      #       <td><code>.topic_01_eval_and_methods</code></td>
      #       <td>Running code strings and dispatching methods dynamically.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - examples/01_basic_eval.cr
      # - examples/03_calling_ruby_methods_and_blocks.cr
      # - src/rubellite/value.cr
      #
      module QUICKSTART
        # **Evaluating Scripts & Invoking Methods**: Running code strings and dispatching methods dynamically.
        #
        # Rubellite offers high-level helpers on `Rubellite` and rich methods on `Rubellite::Value`.
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>API Method</th>
        #       <th>Target</th>
        #       <th>Description</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>`Rubellite.eval(code)`</td>
        #       <td>Global</td>
        #       <td>Parses and executes a Ruby code string</td>
        #     </tr>
        #     <tr>
        #       <td>`value.call(method, *args)`</td>
        #       <td>Object</td>
        #       <td>Invokes a method on a Ruby object with arguments</td>
        #     </tr>
        #     <tr>
        #       <td>`value.call(method) {</td>
        #       <td>blk</td>
        #       <td>... }`</td>
        #       <td>Object</td>
        #       <td>Passes a Crystal block to a Ruby method</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # #### Working Examples
        #
        # ```crystal
        # require "rubellite"
        #
        # Rubellite.init
        #
        # # Define a Ruby class dynamically
        # Rubellite.eval(<<-RUBY)
        #   class Calculator
        #     def add(a, b)
        #       a + b
        #     end
        #
        #     def transform(list, &block)
        #       list.map(&block)
        #     end
        #   end
        # RUBY
        #
        # calc = Rubellite.eval("Calculator.new")
        # sum = calc.call("add", 15, 27)
        # puts "Sum: #{sum.to_i64}" # => 42
        #
        # # Pass a Crystal block to Ruby Enumerable methods
        # array = Rubellite.eval("[1, 2, 3, 4, 5]")
        # doubled = array.call("map") do |item|
        #   item.to_i64 * 2
        # end
        # ```
        #
        # #### Common Pitfalls & Safety Caveats
        #
        # - **Warning**: Ruby exceptions raised in eval or call are wrapped into Crystal `Rubellite::Error` exceptions.
        # - **Warning**: Do not capture long-lived Crystal pointers inside Ruby blocks without pinning.
        #
        # #### Frequently Asked Questions (FAQ)
        #
        # - **Q: How do I catch Ruby errors in Crystal?**
        #   A: Rescue `Rubellite::Error` — it preserves the Ruby exception class name, message, and backtrace.
        #
        def self.topic_01_eval_and_methods : Nil; end
      end
    end
  end
end
{% end %}
