# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Rubellite
  module Docs
    module A_GETTING_STARTED
      # # Quickstart Guide & Usage Patterns
      #
      # This guide provides hands-on code examples for embedding Rubellite into your Crystal project,
      # evaluating Ruby scripts, calling Ruby methods with arguments, and executing blocks.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Evaluating Scripts & Invoking Methods</strong></td>
      #       <td><code>.topic_01_eval_and_methods</code></td>
      #       <td>Running code strings and dispatching methods dynamically with zero boilerplate.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - examples/01_basic_eval.cr
      # - examples/03_calling_ruby_methods_and_blocks.cr
      # - src/rubellite/value.cr
      #
      module QUICKSTART
        # **Evaluating Scripts & Invoking Methods**: Running code strings and dispatching methods dynamically with zero boilerplate.
        #
        # Rubellite offers high-level helpers on the `Ruby` (or `Rubellite`) module and rich ergonomics on `Rubellite::Value`.
        # Initialization is completely automatic: calling `Ruby.eval`, accessing `Ruby["Constant"]`, or invoking `.to_ruby` boots the VM seamlessly on demand.
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>API Method</th>
        #       <th>Target</th>
        #       <th>Description</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>`Ruby.eval(code)`</td>
        #       <td>Global</td>
        #       <td>Parses and executes a Ruby code string (auto-inits VM)</td>
        #     </tr>
        #     <tr>
        #       <td>`Ruby[const_name]`</td>
        #       <td>Global</td>
        #       <td>Resolves a top-level Ruby constant (e.g. `Ruby["JSON"]`)</td>
        #     </tr>
        #     <tr>
        #       <td>`Ruby[const_name]?`</td>
        #       <td>Global</td>
        #       <td>Safely resolves a constant, returning `nil` if undefined</td>
        #     </tr>
        #     <tr>
        #       <td>`value.call(method, *args)`</td>
        #       <td>Object</td>
        #       <td>Invokes a method with protected SEH execution</td>
        #     </tr>
        #     <tr>
        #       <td>`value.call?(method, *args)`</td>
        #       <td>Object</td>
        #       <td>Safe call returning `nil` if an exception occurs</td>
        #     </tr>
        #     <tr>
        #       <td>`value.dig(*keys)`</td>
        #       <td>Collection</td>
        #       <td>Safe nested key retrieval across Hashes and Arrays</td>
        #     </tr>
        #     <tr>
        #       <td>`value.each(&blk)`</td>
        #       <td>Collection</td>
        #       <td>Yields elements to a Crystal block</td>
        #     </tr>
        #     <tr>
        #       <td>`Rubellite.export(name, &blk)`</td>
        #       <td>Global</td>
        #       <td>Exposes a Crystal Proc directly to Ruby as `Rubellite.<name>`</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # #### Working Examples
        #
        # ```crystal
        # require "rubellite"
        #
        # # Auto-initialization: No explicit Rubellite.init needed!
        # json = Ruby["JSON"]
        # parsed = json.call("parse", %({"name": "Rubellite", "tags": ["crystal", "ruby"]}))
        #
        # # Safe nested navigation (interchangeably handles Symbol and String keys)
        # puts parsed.dig("tags", 0).try(&.to_s) # => "crystal"
        #
        # # Bidirectional Crystal function export
        # Rubellite.export("add_numbers") do |args|
        #   (args[0].to_i64 + args[1].to_i64).to_ruby
        # end
        #
        # result = Ruby.eval("Rubellite.add_numbers(19, 23)")
        # puts result.to_i64 # => 42
        # ```
        #
        # #### Common Pitfalls & Safety Caveats
        #
        # - **Warning**: Ruby exceptions raised in eval or call are wrapped into Crystal `Rubellite::Error` exceptions preserving backtraces.
        # - **Warning**: CRuby allows only one initialization per OS process. Automatic initialization manages this safely.
        #
        # #### Frequently Asked Questions (FAQ)
        #
        # - **Q: How do I catch Ruby errors in Crystal?**
        #   A: Rescue `Rubellite::Error` — it preserves the Ruby exception class name, message, and backtrace.
        #
        def self.topic_01_eval_and_methods : Nil; end
      end
    end
  end
end
{% end %}
