# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Rubellite
  module Docs
    module A_GETTING_STARTED
      # # Type Conversions & Value Marshaling
      #
      # Rubellite provides an automatic, zero-copy type mapping system for primitive scalars,
      # alongside deep marshaling for collections like Arrays, Hashes, Tuples, and NamedTuples.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Scalar Primitives & Flonum Encoding</strong></td>
      #       <td><code>.topic_01_scalar_mapping</code></td>
      #       <td>Unboxed 64-bit integer, floating point, boolean, and nil representation.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/rubellite/convert.cr
      # - src/rubellite/value.cr
      # - examples/02_type_conversions_and_hash.cr
      #
      module TYPE_SYSTEM
        # **Scalar Primitives & Flonum Encoding**: Unboxed 64-bit integer, floating point, boolean, and nil representation.
        #
        # Rubellite exploits CRuby's 64-bit tagged pointer representations (USE_FLONUM):
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Crystal Type</th>
        #       <th>Ruby Representation</th>
        #       <th>Tagging Mechanism</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>`Nil`</td>
        #       <td>`Qnil` (0x04)</td>
        #       <td>Immediate constant</td>
        #     </tr>
        #     <tr>
        #       <td>`Bool` (`true` / `false`)</td>
        #       <td>`Qtrue` (0x14) / `Qfalse` (0x00)</td>
        #       <td>Immediate constant</td>
        #     </tr>
        #     <tr>
        #       <td>`Int` (e.g. `Int32`, `Int64`)</td>
        #       <td>`FIXNUM`</td>
        #       <td>LSB tag `0x01` (unboxed 63-bit int)</td>
        #     </tr>
        #     <tr>
        #       <td>`Float64`</td>
        #       <td>`FLONUM`</td>
        #       <td>Bits tagged `0x02` (unboxed double)</td>
        #     </tr>
        #     <tr>
        #       <td>`String`</td>
        #       <td>`T_STRING`</td>
        #       <td>Heap allocated with UTF-8 encoding</td>
        #     </tr>
        #     <tr>
        #       <td>`Symbol`</td>
        #       <td>`ID` / `T_SYMBOL`</td>
        #       <td>Interned symbol ID</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # #### Working Examples
        #
        # ```crystal
        # require "rubellite"
        #
        # Rubellite.init
        #
        # # Convert Crystal scalars to Ruby values
        # val_int = 42.to_ruby
        # val_str = "Hello Crystal".to_ruby
        # val_arr = [1, 2, 3].to_ruby
        #
        # # Unpack Ruby values back into Crystal types
        # puts val_int.as_crystal # => 42_i64
        # puts val_str.as_crystal # => "Hello Crystal"
        # puts val_arr.as_crystal # => [1_i64, 2_i64, 3_i64]
        # ```
        #
        # #### Common Pitfalls & Safety Caveats
        #
        # - **Warning**: Large integers exceeding 63 bits are converted to Ruby Bignum automatically, which incurs heap allocation.
        #
        # #### Frequently Asked Questions (FAQ)
        #
        # - **Q: Can I convert Crystal NamedTuples to Ruby?**
        #   A: Yes, NamedTuples are converted into Ruby Hashes with Symbol keys.
        #
        def self.topic_01_scalar_mapping : Nil; end
      end
    end
  end
end
{% end %}
