# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Rubellite
  module Docs
    module B_ADVANCED_FEATURES
      # # C API, Memory Management & GC Coordination
      #
      # Interfacing Crystal with CRuby requires managing two concurrent runtimes, each equipped
      # with its own garbage collector: Crystal's Boehm-Demers-Weiser GC and Ruby's compacting generational GC.
      #
      # Rubellite implements strict memory safety protocols and Windows MSVC import isolation
      # to eliminate memory corruption, symbol collisions, and dangling references.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Dual-GC Pinning Protocol</strong></td>
      #       <td><code>.topic_01_gc_pinning</code></td>
      #       <td>Protecting Ruby objects held inside Crystal memory structures.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/rubellite/c_api.cr
      # - src/rubellite/gc.cr
      # - src/rubellite/tooling/import_lib_generator.cr
      #
      module C_API_AND_MEMORY
        # **Dual-GC Pinning Protocol**: Protecting Ruby objects held inside Crystal memory structures.
        #
        # Whenever a Crystal struct or class holds a long-lived reference to a `LibRuby::Value`,
        # it must be registered with the Ruby GC to prevent the Ruby collector from sweeping or moving it.
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Mechanism</th>
        #       <th>Function</th>
        #       <th>Purpose</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>**Root Registration**</td>
        #       <td>`rb_gc_register_address`</td>
        #       <td>Pins a pointer address to prevent GC collection</td>
        #     </tr>
        #     <tr>
        #       <td>**Unregistration**</td>
        #       <td>`rb_gc_unregister_address`</td>
        #       <td>Releases the GC root when the Crystal object finalizes</td>
        #     </tr>
        #     <tr>
        #       <td>**Temporary Protection**</td>
        #       <td>`Rubellite::GC.protect { ... }`</td>
        #       <td>Protects local values across complex allocations</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # #### Working Examples
        #
        # ```crystal
        # require "rubellite"
        #
        # # Safe allocation with automatic GC pinning
        # ref = Rubellite::GC.pinned_value(Rubellite.eval("[1, 2, 3]"))
        # # ref is guaranteed not to be moved or collected by CRuby GC
        # ref.free # Cleanly unregisters from GC roots
        # ```
        #
        # #### Common Pitfalls & Safety Caveats
        #
        # - **Warning**: Never pass unpinned Ruby pointers across long-lived Crystal Channels without pinning.
        # - **Warning**: On Windows, always link with ext/ruby_clean.lib to prevent clashing with ucrt symbol definitions.
        #
        # #### Frequently Asked Questions (FAQ)
        #
        # - **Q: What is ruby_clean.lib?**
        #   A: A sanitized import library generated by Rubellite's import_lib_generator to filter out conflicting Win32 symbols.
        #
        def self.topic_01_gc_pinning : Nil; end
      end
    end
  end
end
{% end %}
