# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Rubellite
  module Docs
    module B_ADVANCED_FEATURES
      # # Channel Concurrency & Fiber Interop
      #
      # Crystal utilizes lightweight Fibers with non-blocking event loops, while CRuby relies on
      # native OS threads constrained by the Global VM Lock (GVL / GIL).
      #
      # Rubellite builds a thread-safe bridge (`Rubellite::ChannelBridge`) enabling Crystal fibers
      # to stream values directly into Ruby scripts and vice versa without deadlocking the host process.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>ChannelBridge Architecture</strong></td>
      #       <td><code>.topic_01_channel_bridge</code></td>
      #       <td>Bidirectional asynchronous communication between Crystal fibers and Ruby.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/rubellite/channel.cr
      # - src/rubellite/concurrency.cr
      # - examples/05_channel_and_fiber_concurrency.cr
      #
      module CHANNEL_CONCURRENCY
        # **ChannelBridge Architecture**: Bidirectional asynchronous communication between Crystal fibers and Ruby.
        #
        # The `Rubellite::ChannelBridge` exposes send and receive primitives directly to Ruby scripts:
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Action</th>
        #       <th>Crystal API</th>
        #       <th>Ruby Script Equivalent</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>**Send**</td>
        #       <td>`channel.send(value)`</td>
        #       <td>`Rubellite::Channel.send(channel_id, value)`</td>
        #     </tr>
        #     <tr>
        #       <td>**Receive**</td>
        #       <td>`channel.receive`</td>
        #       <td>`Rubellite::Channel.receive(channel_id)`</td>
        #     </tr>
        #     <tr>
        #       <td>**Close**</td>
        #       <td>`channel.close`</td>
        #       <td>`Rubellite::Channel.close(channel_id)`</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # #### Working Examples
        #
        # ```crystal
        # require "rubellite"
        #
        # Rubellite.init
        #
        # # Create typed Crystal channel
        # chan = Channel(Int32).new
        #
        # # Spawn a background Crystal fiber sending numbers
        # spawn do
        #   5.times do |i|
        #     chan.send(i * 10)
        #     Fiber.yield
        #   end
        #   chan.close
        # end
        #
        # # Register channel in Rubellite bridge
        # bridge_id = Rubellite::ChannelBridge.register(chan)
        #
        # # Consume from Ruby script
        # Rubellite.eval(<<-RUBY)
        #   while (item = Rubellite::Channel.receive(#{bridge_id}))
        #     puts "Ruby received: \#{item}"
        #   end
        # RUBY
        # ```
        #
        # #### Common Pitfalls & Safety Caveats
        #
        # - **Warning**: Always close channels when producers terminate to avoid leaving Ruby consumer fibers hanging.
        #
        # #### Frequently Asked Questions (FAQ)
        #
        # - **Q: Is Channel communication thread-safe?**
        #   A: Yes, Rubellite synchronizes channel access using Crystal spinlocks and mutexes around Ruby GVL transitions.
        #
        def self.topic_01_channel_bridge : Nil; end
      end
    end
  end
end
{% end %}
