# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Rubellite
  module Docs
    module B_ADVANCED_FEATURES
      # # Channel Concurrency & Fiber Interop
      #
      # Crystal utilizes lightweight Fibers with non-blocking event loops, while CRuby relies on
      # native OS threads constrained by the Global VM Lock (GVL / GIL).
      #
      # Rubellite builds a thread-safe bridge (`Rubellite::ChannelBridge`) enabling Crystal fibers
      # to stream values directly into Ruby scripts and vice versa without deadlocking the host process.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>ChannelBridge Architecture & Pipeline Streaming</strong></td>
      #       <td><code>.topic_01_channel_bridge</code></td>
      #       <td>Bidirectional asynchronous communication between Crystal fibers and Ruby with Queue compatibility.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/rubellite/channel.cr
      # - src/rubellite/concurrency.cr
      # - examples/05_channel_and_fiber_concurrency.cr
      #
      module CHANNEL_CONCURRENCY
        # **ChannelBridge Architecture & Pipeline Streaming**: Bidirectional asynchronous communication between Crystal fibers and Ruby with Queue compatibility.
        #
        # The `Rubellite::ChannelBridge` exposes send and receive primitives directly to Ruby scripts:
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Action</th>
        #       <th>Crystal API</th>
        #       <th>Ruby Script Equivalent</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>**Send**</td>
        #       <td>`channel.send(value)`</td>
        #       <td>`queue.send(val)`, `queue.push(val)`, `queue << val`, `queue.enq(val)`</td>
        #     </tr>
        #     <tr>
        #       <td>**Receive**</td>
        #       <td>`channel.receive`</td>
        #       <td>`queue.receive`, `queue.pop`, `queue.deq`, `queue.shift`</td>
        #     </tr>
        #     <tr>
        #       <td>**Safe Receive**</td>
        #       <td>`channel.receive?`</td>
        #       <td>`queue.receive?` (returns `nil` on close)</td>
        #     </tr>
        #     <tr>
        #       <td>**Iteration**</td>
        #       <td>`while val = chan.receive?`</td>
        #       <td>`queue.each {</td>
        #       <td>item</td>
        #       <td>... }` (Enumerable streaming)</td>
        #     </tr>
        #     <tr>
        #       <td>**Close**</td>
        #       <td>`channel.close`</td>
        #       <td>`queue.close`, `queue.closed?`</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # #### Working Examples
        #
        # ```crystal
        # require "rubellite"
        #
        # # Create typed Crystal channel and export to Ruby
        # in_chan = Channel(String).new(10)
        # Rubellite.export_channel("work_queue", in_chan)
        #
        # # Producer fiber
        # spawn do
        #   ["job_alpha", "job_beta", "job_gamma"].each do |task|
        #     in_chan.send(task)
        #   end
        #   in_chan.close
        # end
        #
        # # Ruby consumes using idiomatic Enumerable iteration
        # Ruby.eval(<<-RUBY)
        #   work_queue.each do |task|
        #     puts "Ruby processing \#{task}"
        #   end
        # RUBY
        # ```
        #
        # #### Common Pitfalls & Safety Caveats
        #
        # - **Warning**: Ruby `receive` releases the GVL via `rb_thread_call_without_gvl`, allowing other Ruby threads and Crystal fibers to progress while waiting.
        # - **Warning**: Multi-fiber concurrent evaluations are serialized safely with re-entrant synchronization (`Ruby.synchronize`).
        # - **Warning**: Always close channels when producers terminate to avoid leaving Ruby consumer fibers hanging.
        #
        # #### Frequently Asked Questions (FAQ)
        #
        # - **Q: Is Channel communication thread-safe?**
        #   A: Yes, Rubellite synchronizes channel access using Crystal spinlocks and mutexes around Ruby GVL transitions.
        #
        def self.topic_01_channel_bridge : Nil; end
      end
    end
  end
end
{% end %}
