# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Rubellite
  module Docs
    module B_ADVANCED_FEATURES
      # # Binary Forensics & ABI Auditing via Radare2
      #
      # To prevent subtle runtime segmentation faults caused by mismatched Ruby versions or
      # missing exported symbols, Rubellite integrates directly with radare2 (`r2`).
      #
      # Through `Rubellite::Diagnostics::R2`, developers can inspect shared libraries,
      # disassemble exported functions, and verify ABI compatibility automatically.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Automated ABI & Symbol Auditing</strong></td>
      #       <td><code>.topic_01_r2_auditing</code></td>
      #       <td>Using radare2 to verify Ruby binary exports and detect symbol collisions.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/rubellite/diagnostics/r2.cr
      # - examples/07_r2_binary_forensics.cr
      # - src/rubellite_cli.cr
      #
      module R2_FORENSICS
        # **Automated ABI & Symbol Auditing**: Using radare2 to verify Ruby binary exports and detect symbol collisions.
        #
        # Rubellite's doctor suite performs automated binary forensics:
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Check</th>
        #       <th>Command</th>
        #       <th>Details</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>**Environment Audit**</td>
        #       <td>`rubellite doctor`</td>
        #       <td>Audits Ruby binary, r2 engine, and exported symbols</td>
        #     </tr>
        #     <tr>
        #       <td>**ABI Compatibility**</td>
        #       <td>`r2.audit_environment`</td>
        #       <td>Confirms all required C-API entry points exist</td>
        #     </tr>
        #     <tr>
        #       <td>**Disassembly**</td>
        #       <td>`r2.disassemble_symbol(sym)`</td>
        #       <td>Disassembles MIPS, x86_64, or ARM64 routines</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # #### Working Examples
        #
        # ```crystal
        # require "rubellite"
        #
        # report = Rubellite::Diagnostics::R2.audit_environment
        # puts "Ruby Binary Path: #{report.ruby_dll_path}"
        # puts "Total Symbols Found: #{report.total_symbols_found}"
        # puts "ABI Compatible: #{report.abi_compatible?}"
        # ```
        #
        # #### Common Pitfalls & Safety Caveats
        #
        # - **Warning**: Ensure radare2 (`r2`) is installed in PATH for detailed symbol disassembly output.
        #
        # #### Frequently Asked Questions (FAQ)
        #
        # - **Q: Can Rubellite run if radare2 is not installed?**
        #   A: Yes, radare2 is utilized for forensics and diagnostics; core evaluation functions normally.
        #
        def self.topic_01_r2_auditing : Nil; end
      end
    end
  end
end
{% end %}
