# ==============================================================================
# Auto-generated by Jasper (https://github.com/sol-vin/jasper)
# DO NOT EDIT MANUALLY - Edit source documentation in docs_src/ instead
# ==============================================================================

{% unless flag?(:release) %}
module Rubellite
  module Docs
    module B_ADVANCED_FEATURES
      # # Spinel AOT Native Compilation Fast-Path
      #
      # Spinel is Rubellite's native code generation and fast-path execution engine.
      # For tight loops, mathematical simulations, and cryptographic routines, Spinel bypasses
      # the standard Ruby YARV bytecode interpreter, compiling native LLVM machine code
      # callable directly from either Crystal or Ruby.
      #
      # ### Executive Summary & Key Topics
      #
      # <table>
      #   <thead>
      #     <tr>
      #       <th>Topic</th>
      #       <th>Method / Anchor</th>
      #       <th>Description</th>
      #     </tr>
      #   </thead>
      #   <tbody>
      #     <tr>
      #       <td><strong>Spinel Kernel Compilation</strong></td>
      #       <td><code>.topic_01_spinel_compilation</code></td>
      #       <td>Authoring and compiling native C/LLVM kernels for 10x-50x speedups.</td>
      #     </tr>
      #   </tbody>
      # </table>
      #
      # ### Related Guides & Source References
      # - src/rubellite/spinel.cr
      # - examples/06_spinel_aot_fastpath.cr
      #
      module SPINEL_AOT
        # **Spinel Kernel Compilation**: Authoring and compiling native C/LLVM kernels for 10x-50x speedups.
        #
        # Spinel supports compiling native C algorithms into shared dynamic libraries loaded at runtime:
        #
        # <table>
        #   <thead>
        #     <tr>
        #       <th>Feature</th>
        #       <th>Standard Ruby</th>
        #       <th>Spinel AOT Fast-Path</th>
        #     </tr>
        #   </thead>
        #   <tbody>
        #     <tr>
        #       <td>**Execution**</td>
        #       <td>YARV Bytecode / JIT</td>
        #       <td>Native LLVM Machine Code</td>
        #     </tr>
        #     <tr>
        #       <td>**Boxing Overhead**</td>
        #       <td>Object allocation</td>
        #       <td>Zero unboxed scalar math</td>
        #     </tr>
        #     <tr>
        #       <td>**Speedup**</td>
        #       <td>Baseline 1.0x</td>
        #       <td>10x - 50x for numerical kernels</td>
        #     </tr>
        #   </tbody>
        # </table>
        #
        # #### Working Examples
        #
        # ```crystal
        # require "rubellite"
        #
        # # Compile a native Fibonacci function via Spinel
        # kernel = Rubellite::Spinel.compile_c(<<-C)
        #   long long fib(long long n) {
        #     if (n <= 1) return n;
        #     return fib(n - 1) + fib(n - 2);
        #   }
        # C
        #
        # res = kernel.call("fib", 35_i64)
        # puts "Fib(35): #{res}"
        # ```
        #
        # #### Common Pitfalls & Safety Caveats
        #
        # - **Warning**: Spinel requires an available C compiler (clang, gcc, or MSVC cl.exe) when compiling dynamic kernels on the fly.
        #
        # #### Frequently Asked Questions (FAQ)
        #
        # - **Q: What happens if a native C compiler is not found?**
        #   A: Rubellite falls back gracefully to pure Crystal or Ruby interpreted implementations.
        #
        def self.topic_01_spinel_compilation : Nil; end
      end
    end
  end
end
{% end %}
